name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.2
          - 28.1
          - 29.1
          - snapshot
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-python@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - name: Compile
      run: make compile
